### ISSUE TITLE
Shutdown via Finder App

### ISSUE THREAD

**Issue by toddtreece** [adafruit/Adafruit-Pi-Finder#17]
via [the beta blog post](https://www.adafruit.com/blog/2015/01/23/help-us-test-our-new-raspberry-pi-bootstrap-piday-raspberrypi/#comment-284445):

> The bootstrap works great on my Model B Rev 1.0. This program will be VERY handy. How about adding a convenient “Shutdown” button to gracefully shut down the Raspberry Pi?

**Comment by ladyada** [comment]
this is really a good idea - i'll put my vote in for it! :)

**Comment by tdicola** [comment]
Oh yeah I would love that--it's something we were thinking of adding to the web IDE but would be great here too.
