### ISSUE TITLE
finding wifi pi

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit-Pi-Finder#29]
on the off chance i have to try to find a pi and its on wifi but i cant get to the .local address...
is there some way to detect ping responses, then check for ip's with ssh port open maybe fingerprint some other way without using MAC...

**Comment by toddtreece** [comment]
This was fixed by 53ca7fbe4eeaef188d69db54b163e1c1b8d2356c. We can add more advanced detection in the future, but that should take care of the Adafruit WiFi modules.
