### ISSUE TITLE
upload test

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit-Pi-Finder#30]
![complete](https://cloud.githubusercontent.com/assets/1214161/5993943/e6ba79e8-aa2f-11e4-896d-53c33d1be51f.png)

seems to work but umm maybe could use some ncurses? :)

**Comment by ladyada** [comment]
shoot... :(
![sad](https://cloud.githubusercontent.com/assets/1214161/5993968/09756456-aa31-11e4-994b-5e58d48473e8.png)

**Comment by toddtreece** [comment]
@ladyada the [1.2-beta pre-release](https://github.com/adafruit/Adafruit-Pi-Finder/releases/tag/v1.2-beta) has new builds that should fix the upload percent display issue. How big was the file you sent?

**Comment by ladyada** [comment]
lol i ran out of space, sorry i thought it was a 500K file but it was 500M. whee! go pats!

are you using scp or 'hand-transferring'?

**Comment by toddtreece** [comment]
@ladyada i'm using a JS implementation of the SSH file transfer protocol. i can check to see if the version implemented allows for checking the free space available on the target pi

**Comment by ladyada** [comment]
hmm i downloaded the pibootstrap 1.2 like an hour ago - should i grab it again to test the curses thing?

**Comment by brennen** [comment]
> i can check to see if the version implemented allows for checking the free space available on the target pi

Maybe just an invocation of `df` on the target first?

**Comment by toddtreece** [comment]
@brennen yeah. i was hoping to avoid parsing the output of `df`, but I guess I could do all of the prep in bash first and read the output.

@ladyada i replaced them right before commenting, but i don't think there's a reason to grab them just to test that. i'm pretty sure that bug is fixed.

**Comment by brennen** [comment]
> but I guess I could do all of the prep in bash first and read the output.

Hmm, yeah. Maybe:

```
brennen@exuberance 16:19:15 /home/brennen $  df /home --output=avail | tail -1
128297852
```

**Comment by toddtreece** [comment]
@brennen the installed version of `df` doesn't have `--output`. this is the best i could come up with:
```
df /home/pi | tail -1 | tr -s ' ' | cut -f 4 -d ' '
```

**Comment by toddtreece** [comment]
this issue should be fixed in [v1.2.1-beta](https://github.com/adafruit/Adafruit-Pi-Finder/releases/tag/v1.2.1-beta)

**Comment by ladyada** [comment]
all fixed & tested!

**Comment by toddtreece** [comment]
thanks!
