### ISSUE TITLE
plz change to -h

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit-Pi-Finder#33]
https://github.com/adafruit/Adafruit-Pi-Finder/blob/master/pi_finder/src/ssh.js#L90

add -h for total halt plz so LED will blink n stuff.

**Comment by toddtreece** [comment]
added in [v1.2.2-beta](https://github.com/adafruit/Adafruit-Pi-Finder/releases/tag/v1.2.2-beta)

**Comment by toddtreece** [comment]
it will be nice when the auto-update feature is finished so these releases are applied without having to re-download the giant atom-shell wrapper

**Comment by toddtreece** [comment]
fixed by f71fd38a08d071a5679a60d837e74f5d2822ecc4
