### ISSUE TITLE
pifinder v2 on windows some issues on 'bootstrap' button click

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit-Pi-Finder#35]
![on bootstrap](https://cloud.githubusercontent.com/assets/1214161/6026879/28dfcc60-abac-11e4-9f17-032e9d346ba0.png)

![terminal](https://cloud.githubusercontent.com/assets/1214161/6026888/40b24160-abac-11e4-8d99-50c7858b310d.png)

**Comment by toddtreece** [comment]
@ladyada that bug was there just to test out auto updates :) if you restart the app, the update will be pulled and that should fix the issue.

**Comment by ladyada** [comment]
cool works now!
