### ISSUE TITLE
Guide to compile on Windows (spawn ENOENT on plistbuddy fix)

### ISSUE THREAD

**Issue by maditnerd** [adafruit/Adafruit-Pi-Finder#46]
If you happens to build Adafruit-Pi-Finder on Windows and have the same error than me, here is how to fix it.

# Compile Adafruit-Pi-Finder

* I downloaded node.js from the official source : https://nodejs.org/download/
* And type theses commands inside Adafruit-Pi-Finder/pi_finder/main
```` 
npm install -g grunt-cli
npm install
grunt build --force
````

Which gave me this error:
![image](https://cloud.githubusercontent.com/assets/2841495/6656124/8fb5ee2a-cb1d-11e4-8cde-7a93cb327a13.png)

# Fix error
Comment every reference to plistbuddy inside **Gruntfile.js** and it should works

[L142](https://github.com/adafruit/Adafruit-Pi-Finder/blob/master/pi_finder/main/Gruntfile.js#L142)
````
//grunt.loadNpmTasks('grunt-plistbuddy');
````
[L149](https://github.com/adafruit/Adafruit-Pi-Finder/blob/master/pi_finder/main/Gruntfile.js#L149)
````
grunt.registerTask('build', ['clean:all', 'build-atom-shell-app', 'rename', 'copy', 'chmod', /*'plistbuddy',*/ 'winresourcer', 'compress']);
````

This won't compile the MACOS version but I don't think this is possible on Windows :-(

# Test your modification

## Remove autoupdater
Each times Adafruit-Pi-Finder starts it will reset adafruit-pi-finder folder to the original version.   
you need to comment this part to avoid this.

**main/main.js**   
L13/L21       
````
  //npm.commands.install(__dirname, ['adafruit-pi-finder@latest'], function(err) {

   //   if(err) {
   //     return dialog.showErrorBox('ERROR', 'Pi Finder auto update failed! Are you connected to the internet?');
   //   }

      require('adafruit-pi-finder')(app);

    //});
````

## Install atom-shell client

You will need to install **atom-shell** to test your application **without compiling it**.
**inside pi_finder type**

````
npm install atom-shell -g
atom-shell main
````

**Comment by toddtreece** [comment]
@maditnerd thanks for your notes! i'll switch out plistbuddy once i get a chance to get back to working on pi finder. the grunt task just downloads the prebuilt atom shell binaries for each OS and modifies them, so i think i could probably fix this issue by using something more generic for replacing strings in the plist files for the mac build
