### ISSUE TITLE
Cannot Paste into Terminal

### ISSUE THREAD

**Issue by AtomicLaser** [adafruit/Adafruit-Pi-Finder#49]
On OSX 10.10.3 (Yosemite) I'm unable to copy and paste into the terminal window using the keyboard shortcuts  + c or  + v

The edit >> copy/paste functions works from the top menu.

This works in the standard mac terminal, so not sure why this doesn't work in the Pi-Finder terminal.

**Comment by toddtreece** [comment]
@AtomicLaser If you are using v2 or higher, you should be able to just reopen the Pi Finder and the auto-update should pull this fix. If not, you will have to download the latest release.

**Comment by AtomicLaser** [comment]
This issue seems to have come back again, plus pifinder doses't scroll properly on OSX

Is this still developed?
